server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri.html $uri/ =404;

    add_header Cache-Control "no-cache, must-revalidate";
  }

  location /_next/static/ {
    root /usr/share/nginx/html;
    add_header Cache-Control "public, max-age=2592000, must-revalidate";
  }

  location ~* \.(jpg|jpeg|png|webp|avif|svg|ico)$ {
    root /usr/share/nginx/html;
    add_header Cache-Control "public, max-age=604800, stale-while-revalidate=86400";
  }
}